### ISSUE TITLE
modrinth-app doesn't seem to have internet access?

### ISSUE THREAD

**Issue by janTasija** [getchoo/nix-exprs#29]
hi! i tried installing your modrinth-app package and it looks like this, not sure if it's supposed to?
<img width="635" alt="image" src="https://github.com/getchoo/nix-exprs/assets/53832230/89655066-ac3b-41a6-84f1-9b2bd07952c7">

**Comment by getchoo** [comment]
could you launch this from the command line and post anything that's outputted by the app? it'll hopefully give more information as to what's going on in the background here. also are you on nixos or a different distribution?

without that for now though, my guess is that this is the unwrapped version of the package, which won't have the proper wrapper to enable networking and other things. make sure you're using `modrinth-app` and not `modrinth-app-unwrapped`

**Comment by getchoo** [comment]
is the package installed as an overlay or the nixpkgs input overridden? ideally this shouldn't be possible when running directly from the flake

**Comment by getchoo** [comment]
it seems this was an issue in the way the app was wrapped with glib-networking's gio modules. this should be fixed now
